### ISSUE TITLE
use a framework for tests

### ISSUE THREAD

**Issue by ichiriac** [glayzzle/php-parser#10]
Need to improve tests codes with some use cases and get the tests driven development simpler :
- coverage will be generated with istanbul
- automatic coverage tests will be done with coveralls
- functionnal tests will be done with mocha

Will add a new symphony framework for generic parsing abilities

**Comment by nevadascout** [comment]
I've made a start on the functional tests with Mocha, see PR #13.

**Comment by ichiriac** [comment]
Really thanks, you saved me a lot of time. 

I will continue to improve tests - actually builds fails because of travis and the deployment of php7 with apt ... 

By the way, symphony parsing passes - that's why I've started to test with php7

**Comment by nevadascout** [comment]
The mocha tests should be run as part of the CI build as well, the `.travis.yml` file needs updating :)

**Comment by ichiriac** [comment]
mocha tests are now included into the coverage process and can also be run with `node bin/test.js -m test/functional`

Remains some coverage to be done, but I close the issue, testing tools are running
