### ISSUE TITLE
Idea: implement php formatting support in prettier

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#100]
Prettier is great and popular tool https://github.com/prettier/prettier.

This will increase the popularity of the package and possibly help find sponsors. I can help with this, but there's a lot of work to do, just let me know if you like this idea. Thanks for this great package!

---

Python https://github.com/prettier/prettier/pull/3349.

**Comment by mgrip** [comment]
I've actually already started 😄  (hence why I'm following this repo) https://github.com/prettier/prettier#3521

**Comment by evilebottnawi** [comment]
@mgrip awesome!

**Comment by evilebottnawi** [comment]
@mgrip don't stop this PR, if you need help just ping me :+1:

**Comment by mgrip** [comment]
thanks @evilebottnawi! there's some discussion from the core contributors about how prettier is going to scale with other languages, but i _think_ at least the printer piece of this is still going to be viable. if you feel like working on a PR i certainly won't turn away help! https://github.com/mgrip/prettier/pull/1#pullrequestreview-85375143 as an example

**Comment by ichiriac** [comment]
Hi guys, I like the idea :+1: - just for information, actually there is an implementation for convert back AST to code, it maybe help you : https://github.com/chris-l/php-unparser

**Comment by mgrip** [comment]
thanks @ichiriac! we get a lot of stuff for free by building on the core prettier project - but will definitely take a look at that project to see if there's anything we can learn from it!

**Comment by evilebottnawi** [comment]
We can close this issue in favor https://github.com/prettier/plugin-php
