### ISSUE TITLE
how to access property promotion in php8 ?

### ISSUE THREAD

**Issue by ctf0** [glayzzle/php-parser#1048]
for example a class like
```php
final class CurrencyFactory
{
    private $currencyList;

    /**
     * @param array<string, mixed> $currencies
     */
    public function __construct(private array $currencies)
    {
    }
}
```

- parser config
```js
const parser = new PhpParser.Engine({
    parser: {
        extractDoc: true,
    },
    ast: {
        withPositions: true
    }
});
```

the `propertystatement` only have `$currencyList`, but how to get `$currencies` info aswell?

am not sure if this is a bug or am missing a config option, any help is appreciated.

**Comment by deakjahn** [comment]
`PropertyStatement` has an array of `Property` items, in your case it will have one item, actually.

But I can't really see why you look for `$currencies` in the property declaration. That will be something totally different, namely, one of the `Parameter` items of a `Method`.

**Comment by ctf0** [comment]
isnt it considered as a class property? still, I managed to get it as a constructor argument but it doesnt have a visibility key, which is why it should be under the class properties instead,because without that key we cant differentiate if its a property promotion or a param.

**Comment by deakjahn** [comment]
Yes and no. I suspect that you expect much more from a parser than it actually does. An AST doesn't give you any such processing, it's nothing else than a direct representation of the source code itself. You have to walk the tree, recursively, and process each and every node to collect whatever pieces of information you want to collect, that's up to you.

For instance, the `Class` has a body that is an array of `Declaration` items. You enumerate those one by one and check each one. Some might be properties, others could be constants and some will be methods. If it's a method, it will have arguments and each argument can have a visibility flag.

Practically, if you want to process a syntax tree, you need to have a handler function with a huge switch with _all_ possible items:

    switch (node.kind) {
      case 'array':
        return this.array(node as php.Array);
      case 'arrowfunc':
        return this.arrowfunc(node as php.ArrowFunc);
      case 'assign':
        return this.assign(node as php.Assign);
      case 'assignref':
        return this.assignref(node as php.AssignRef);
      ....
      }

that calls a handler function for any of the posible node types of interest to you, processes it, collects whatever pieces of information you need to extract or store, and also make sure that you call your handler recursively for any node type that has additional fields, a body or anything similar.

**Comment by ctf0** [comment]
i know what you mean and i do that ex. parsing an array to symbols but regarding the property promotion, its a combination of a property and an argument, the only difference is the visibility, atm its not there, if u can give me an example where u see that flag plz do.

**Comment by deakjahn** [comment]
https://github.com/glayzzle/php-parser/blob/3ff45606965cffad06931bb10e62e6baffd0de43/types.d.ts#L725-L734

**Comment by ctf0** [comment]
@deakjahn many many thanks for your help & quick response, deeply appreciate it.
