### ISSUE TITLE
Add to string node `raw` contain raw value with escaped special characters

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#116]
Example we have `$a= "foo\nbar"`:
value = `foo\nbar`;
raw = `"foo\\nbar"`

All popular parser do this https://astexplorer.net/#/gist/070b3c0b39f0af268d909e3ba9efa2a3/2ba4c9d3ab6b3e3cf31f6148a28966c638948790

Ref: https://github.com/prettier/plugin-php/pull/57 

Thanks!

**Comment by ichiriac** [comment]
Hi @evilebottnawi,

I agree with you as you can loos information without the raw attribute :

![image](https://user-images.githubusercontent.com/173203/36420644-00af0600-1636-11e8-9af8-2edc5ee0ed28.png)

**Comment by evilebottnawi** [comment]
@ichiriac need help?

**Comment by ichiriac** [comment]
yes, any help would be verry appreciated

**Comment by evilebottnawi** [comment]
@ichiriac `raw` or `rawValue` property?

**Comment by ichiriac** [comment]
I vote for `raw` - more concise

**Comment by evilebottnawi** [comment]
@ichiriac can you help with this? we have a lot of work in prettier, it is problem have maximum priority

**Comment by evilebottnawi** [comment]
Also strange:
```php
a = 'You deleted C:\\*.*?';
```

Contain: `You deleted C:\*.*?`

**Comment by ichiriac** [comment]
Not sure yet on single quotes, but \ is for escaping, so \\ resolves as a single \ - have a try on php cli but i'm almost sure it's correct

**Comment by ichiriac** [comment]
this feature is now implemented over `literals` nodes including :
 - Boolean
 - String
 - Number (attribute ignored for the moment as it's always the same - needs investigation)
 - Inline
 - Magic (value is allways uppercase)
 - Nowdoc
 - Encapsed

I need to better cover them with tests, I'll do it later
