### ISSUE TITLE
public always true

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#118]
Input:
```php
class MyClass
{
    function myFunction() 
    {
        // Nothing
    }
}
```

`function` always interpreted as `public`. Maybe we can add `hiddenVisibility: true` (maybe best name)? 

Based https://github.com/prettier/plugin-php/issues/72

**Comment by ichiriac** [comment]
Yes, I could disable https://github.com/glayzzle/php-parser/blob/master/src/parser/class.js#L248 so when not public keyword is used, the visibility flag could be -1.

**Comment by evilebottnawi** [comment]
@ichiriac will be great :+1:

**Comment by ichiriac** [comment]
@evilebottnawi, now the visibility property is empty when the keyword is not defined.

**Comment by evilebottnawi** [comment]
@ichiriac thanks!

**Comment by evilebottnawi** [comment]
@ichiriac it is work for const `public const OTHER_CONST = 'value';` ?

**Comment by ichiriac** [comment]
@evilebottnawi yes, the visibilty should be `node.visibility = "public"` in this case

**Comment by evilebottnawi** [comment]
@ichiriac can you release patch with this changes?

**Comment by ichiriac** [comment]
I will work on php-parser bug this week, and I'll release it under 3.0.0-alpha

**Comment by evilebottnawi** [comment]
@ichiriac Awesome :+1:
