### ISSUE TITLE
It is not possible to determine int or integer and etc in cast

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#119]
Input:
```php
$bar = (integer) $foo;
```
Contain `type: 'int'`. Maybe add property `raw`, which contain real type?

**Comment by ichiriac** [comment]
+1 for raw, could also be `$bar = (InTeGeR) $foo;` as keywords are not case sensitive

**Comment by mgrip** [comment]
can i vote to move to `3.1.0`? Should be a non-breaking change to add the raw property

**Comment by evilebottnawi** [comment]
@mgrip i think better use `prerelease` tag, i think we can have other request on modify ast

**Comment by ichiriac** [comment]
ok, the next one will be a 3.0.0-prerelease.1 as the alpha stage is way behind on this version
