### ISSUE TITLE
Inline value is not fully

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#120]
Seems it is bug. Inline value don't contain first newline which following after `?>` tag
Input:
```php
function bar() {
  ?>
  <span>Hello World!</span>
  <?php
}
```

Contain: `value: '  <span>Hello World!</span>\n  '`. __BAD__ (should be `value: '\n  <span>Hello World!</span>\n  '`)

Input:
```php
function inline() {
  ?><span>Hello World!</span><?php
}
```

Contain: `value: '<span>Hello World!</span>'`. __GOOD__

Input:
```php
function foo() {
    ?>
    <span>Hello World!</span>
    <?php
}
```

Contain: `value: '    <span>Hello World!</span>\n    '`. __BAD__ (should be `value: '\n    <span>Hello World!</span>\n    '`)

**Comment by ichiriac** [comment]
Hi, it's not really a bug, as it mimics PHP output behavior based on lexer tokens (strictly the same as php token_get_all). 

I'm not sure to understand why PHP do this (maybe something related with indenting outputs), but I'm totally agree with you, it introduce information loss.

I will not change the lexer as it's supposed to work as PHP, but I could fix it from AST and revert back the missing line break.

**Comment by evilebottnawi** [comment]
@ichiriac 
> I will not change the lexer as it's supposed to work as PHP, but I could fix it from AST and revert back the missing line break.

Will be great!

**Comment by ichiriac** [comment]
fixed with the `raw` attribute
