### ISSUE TITLE
Support array destructuring

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#121]
```php
[$id1, $name1] = $data[0];
```

```php
["id" => $id1, "name" => $name1] = $data[0];
```

Ref: http://php.net/manual/en/migration71.new-features.php

**Comment by mgrip** [comment]
omg I'm learning so much about php through this javascript plugin 🤣

**Comment by ichiriac** [comment]
- Entry starting here : https://github.com/php/php-src/blob/master/Zend/zend_language_parser.y#L875 
- Rules defined here : https://github.com/php/php-src/blob/master/Zend/zend_language_parser.y#L1207
- Implementation expected : https://github.com/glayzzle/php-parser/blob/d1e3e4aa3a4b9b1b77e202a305dd30fa8adc23cd/src/parser/expr.js#L143
