### ISSUE TITLE
Eval ignores closing tag

### ISSUE THREAD

**Issue by thiagorb** [glayzzle/php-parser#127]
Input:

    echo "hello"; ?> world

Running the code above in PHP's eval would result in:

    php > eval('echo "hello"; ?> world');
        hello world

But the parser is failing with syntax error.

I also noticed that the following code will not result in error, and generates an AST with no children, while it should contain '?>?>' as inline:

    parser.parseEval(`?>?>?>`)

**Comment by ichiriac** [comment]
Hi @thiagorb,

Thanks for the report, it's fixed now and will be released on v3.0.0 soon
