### ISSUE TITLE
Don't detect when echo inside mixed content

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#129]
Input:
```php
<div>
<?= 'test'; ?>
</div>
<?php
echo 'test;
```

Maybe we can add `node.shortForm` (or maybe `node.alternativeForm`) for this?

**Comment by ichiriac** [comment]
+1 for `shortForm` it's actually not used on echo tags, and makes reference to other short forms usually used for templating

**Comment by ichiriac** [comment]
fixed - will be released soon
