### ISSUE TITLE
Forward slash escaping

### ISSUE THREAD

**Issue by mgrip** [glayzzle/php-parser#130]
I'm not exactly sure whats going wrong here, but it seems like maybe an unescaped forward slash is still getting escaped in the parser?

![image](https://user-images.githubusercontent.com/13454680/37164999-8d1fd976-22c9-11e8-8fba-e0d5baf7b310.png)

**Comment by evilebottnawi** [comment]
Seems related:
```php
$string =  '\/';
```
Parsed as `"\\/"`

**Comment by ichiriac** [comment]
Hi @mgrip,

I'll check it but on the ast explorer they use the latest release, and the bugfix is not yet released. Try with the latest master version and check the `raw` property, in principle it should work.

**Comment by mgrip** [comment]
Will do, thanks for the heads up!
