### ISSUE TITLE
The comments disappear if there is an inline before the code

### ISSUE THREAD

**Issue by chris-l** [glayzzle/php-parser#131]
Hi!

If I try to parse this:

```php
<?php
// a comment
/* bbb */
echo 1;
```
it correctly parses the comments. However, if I add an inline text before the `<?php`, the comments disappear from the AST.

```php
xx<?php
// a comment
/* bbb */
echo 1;
```

With that `xx` at the begin, the comments are no longer present on the AST. I have test it on your AST explorer, and directly using the package, the 2.2.0 version.

**Comment by ichiriac** [comment]
Hi Chris,

You are right about the bug in the 2.x - but it was fixed on master.

Take a look at this issue : https://github.com/glayzzle/php-parser/issues/126#issuecomment-370268380 I'm introducing a new feature for the next release.

The online version https://glayzzle.com/php-parser/ uses the latest release, check comments and try your code. It will output :

PHP Script :
```php
xx<?php
// a comment
/* bbb */
echo 1;
```

AST Structure :
```json
{
  "kind": "program",
  "children": [
    {
      "kind": "inline",
      "value": "xx",
      "raw": "xx"
    },
    {
      "kind": "echo",
      "leadingComments": [
        {
          "kind": "commentline",
          "value": "// a comment\n"
        },
        {
          "kind": "commentblock",
          "value": "/* bbb */"
        }
      ],
      "arguments": [
        {
          "kind": "number",
          "value": "1"
        }
      ],
      "shortForm": false
    }
  ],
  "errors": [],
  "comments": [
    {
      "kind": "commentline",
      "value": "// a comment\n"
    },
    {
      "kind": "commentblock",
      "value": "/* bbb */"
    }
  ]
}
```

**Comment by chris-l** [comment]
ohh, it seems you are completely changing the way comments are handled.

That also will allow to parse (and conserve the comments) on things like this:

```php
function mul
// This is a fn
($a, // The value of $a
$b  // The value of $b
) {
echo $a * $b;
}
```

The way the AST is delivered now on the new parser is stable now? That is, is a good idea if I start to look around the new AST, or it may change more before v3.0.0 is released?

And, will something else, besides the comments, change on this new version?

**Comment by ichiriac** [comment]
Hi Chris,

The comments structure are stable, but they will be improved by adding new features (for example https://github.com/glayzzle/php-parser/issues/135) so if you change your code using actual master code it will be compliant with the next release.

Also main other changes are : introduced also a `raw` property for strings, and new properties on some nodes. 

You can take a look here to have a complete list of changes :
https://github.com/glayzzle/php-parser/milestone/10?closed=1

Fell free to submit requests if you need something as I want the next release to be a long term structure and avoid to introduce breaking changes after.
