### ISSUE TITLE
Heredoc quotes loose

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#133]
Input:
```php
$string = <<<"EOJS"
some text
should not indent
EOJS;
```

Output: https://astexplorer.net/#/gist/070ed89ca1b5b086a5bb38b51c29fc97/e657ffae5e79c99cabacb499911d7375b7a11f2c

**Comment by ichiriac** [comment]
If you try this on the [next release](https://glayzzle.com/php-parser/#demo) you will see that you have a `raw` property but it does not include the <<<"EOJS" (because I've eaten the token token too early but can be fixed) - so you could use this one.

I could also add a `quote` boolean property

**Comment by evilebottnawi** [comment]
@ichiriac `quote` willl be great!

**Comment by ichiriac** [comment]
it's done
