### ISSUE TITLE
Bug with parsing `list`

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#137]
Input:
```php
list(,$power) = $info;
```
```php
list($power) = $info;
```

Have same count of arguments

**Comment by ichiriac** [comment]
Not sure yet, but it may come from an abusive usage of a too permissive reader implemented here https://github.com/glayzzle/php-parser/blob/master/src/parser/utils.js#L30

If it's the case, the problem can reproduced on others nodes, I need to check each `read_list` usage

**Comment by evilebottnawi** [comment]
@ichiriac Can we fix it next? We have many problem in `prettier-php` with this construction, many people use this

**Comment by ichiriac** [comment]
it's fixed - i will release an alpha 2 in few days
