### ISSUE TITLE
3.0 Usegroup location is wrong

### ISSUE THREAD

**Issue by mgrip** [glayzzle/php-parser#139]
![image](https://user-images.githubusercontent.com/13454680/37739092-6baf91f8-2d2f-11e8-8857-91664dd85a51.png)

Seems like the usegroup loc end is inclusive of comments that fall after it (don't think it should)

**Comment by mgrip** [comment]
Interestingly enough, it only happens when the `extractDoc: true` setting is enabled. When its not, the `locEnd` is correctly parsed as 4

**Comment by ichiriac** [comment]
it's fixed

**Comment by mgrip** [comment]
awesome thanks @ichiriac!
