### ISSUE TITLE
`break` propertylookup break parsing

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#148]
Input:
```php
$a = new stdClass();
$a->break = 1;

echo $a->
    break;
```

Output: `Parse Error : syntax error, unexpected 'break' (T_BREAK) on line 7`. But it is valid code.

**Comment by ichiriac** [comment]
related to https://github.com/glayzzle/php-parser/issues/91, fails if contains a T_WHITESPACE token.

**Comment by ichiriac** [comment]
it's fixed
