### ISSUE TITLE
Binary cast: isDoubleQuote incorrect

### ISSUE THREAD

**Issue by czosel** [glayzzle/php-parser#149]
I would expect `isDoubleQuote: true` here:
![image](https://user-images.githubusercontent.com/7962156/38620469-d0b9dafc-3d9e-11e8-90c8-082cc56214a3.png)

**Comment by ichiriac** [comment]
** Breaking Changes **
---

Before `b"$var"` does use a binary node, and the raw encapsed node does not include the `b` prefix.

From this commit, the binary encapsed nodes are no more into a binary node and the raw property includes the `b` prefix.

Next I will have to include the unicode property on encapsed nodes also, as explained here : https://github.com/glayzzle/php-parser/issues/147
