### ISSUE TITLE
Add a support for a graceful parsing mode

### ISSUE THREAD

**Issue by ichiriac** [glayzzle/php-parser#15]
Like explained into this thead :
https://github.com/glayzzle/php-parser/pull/12

Introducing a new AST node type :
`["error", tokenName, [expected...], lineNumber]`

To enable to option we could write (disabled by default) :

```
var ast = parser.parseEval('...some code...', {
  parser: {
    gracefull: true
  }
})
```

**Comment by ichiriac** [comment]
I've changed the way to activate this mode (needs to be encapsulated and runs code) :

```
    var test = parser.create();
    test.parser.gracefull(true);
```

By using a decorator, no need to update the code logic, and avoid performance issues when this mode is not enabled.

You have at the program level @ 2 offset the list of all errors, it also tries to return the error as AST (injection of the node into the code AST depends on the way the code is written)

Needs to be tested a lot I think :)

**Comment by nevadascout** [comment]
Commit 8fa16c50d looks good, but you're right - this needs a lot more tests :)

**Comment by ichiriac** [comment]
extra '}' will break class / namespaces / functions scopes - some next tokens will fall into parse errors but without a real reason :

```php
<?php
class foo {
  private function bar() {
    if ($this->baz) // <-- expect here a { or : or ;
    } // <-- end of function
  } // <-- end of class
  public function foobar() { // <-- public should not be used outside a class
  }
} // <-- unexpected bracket here
```

First parse error is correct, but others should be ignored because they are not real ones.
