### ISSUE TITLE
Bump 3.0 alpha

### ISSUE THREAD

**Issue by mgrip** [glayzzle/php-parser#160]
👋 wondering if you wouldn't mind bumping the version for the 3.0 alpha? Trying to start using https://github.com/prettier/plugin-php without the github dependencies.

**Comment by mgrip** [comment]
Actually didn't realize you had already published `alpha2`, thanks!

**Comment by ichiriac** [comment]
hi @mgrip, you're right about releasing an official 3.0 update. I still need to make some fixes and then release a final version. I'm actually too busy to work on it but maybe in next few weeks or this summer
