### ISSUE TITLE
declare doesn't support inline nodes

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#165]
Input:
```php
<?php
declare(ticks=1) {
    ?>
    Foo bar
    <?php
}
```

**Comment by ichiriac** [comment]
Hi @evilebottnawi,

I don't understand what's the problem, it's parsing without errors :
![image](https://user-images.githubusercontent.com/173203/43354787-ab93b08c-9252-11e8-88cc-ebe7fcf50a75.png)

**Comment by evilebottnawi** [comment]
Bug was on our side
