### ISSUE TITLE
cast precedence

### ISSUE THREAD

**Issue by ichiriac** [glayzzle/php-parser#172]
Handle cast precendence :

```php
<?php
$a = (string)$foo . $a;
// actual behaviour
$a = (string)($foo . $a);
// expected behaviour
$a = ((string)$foo) . $a;
```

Cast includes function calls, object operators, arrays.

**Comment by evilebottnawi** [comment]
@ichiriac Can we solve this problem in near future. When we introduce better print parens (based on `parenthesizedExpression`) login in `prettier` it is output a lot of bugs :disappointed:

**Comment by ichiriac** [comment]
yes, sorry, I had not much time to work on php-parter later - I'll be back soon

**Comment by evilebottnawi** [comment]
Also problem with `retif`:
```php
(bool) $var ? 1 : 2;
(bool) ($var ? 1 : 2);
```

**Comment by evilebottnawi** [comment]
Also same problem for `silence` node. Related https://github.com/glayzzle/php-parser/issues/195
