### ISSUE TITLE
Don't output `null` for last element in `list/array`

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#174]
Input:
```
list(,$first, $second, $three, $fourth,) = $arr;
```

Contain `null` in `arguments`.

Babylon example: https://astexplorer.net/#/gist/6d37953c6b42f02a3ffe48b6101127c3/745b62f49d2c011d789e6d9754a4d705db5cdab0

I think it is unnecessary, because it is doesn't have sense for executing/parsing/printing/etc.

**Comment by ichiriac** [comment]
You're right about stripping null items from the end

**Comment by evilebottnawi** [comment]
@ichiriac looks `null` still exists after upgrading to `3.0.0-prerelease.4` :confused:

**Comment by ichiriac** [comment]
:grinning: sorry, i'll check this next week, this week-end i'm bussy, not at home. I'll keep you in tuch

**Comment by evilebottnawi** [comment]
@ichiriac :+1: Thanks!

**Comment by ichiriac** [comment]
Hi, 

I could strip them, but without node you may loose comments, here an example :

```php
<?php
list($a, $b, /* arg3 */, /* arg 4 */) = [1,2,3,4];
```

It's better to introduce a Noop node that could bind at the right place the comment (could also be used on empty functions bodies in order to attach on it the comment

**Comment by evilebottnawi** [comment]
:+1:

**Comment by ichiriac** [comment]
It's fixed & will be released soon

**Comment by evilebottnawi** [comment]
@ichiriac maybe not right place, but just want put here with list problems for use https://github.com/prettier/plugin-php/issues/854

**Comment by evilebottnawi** [comment]
php7.3 was released very long time age and we sill doesn't support many features

**Comment by ichiriac** [comment]
ok, that was referenced under #345 & #346
