### ISSUE TITLE
impossible detect curly in `encapsed`

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#175]
Input:
```php
$juices = ['FOO' => 1];

echo "He drank some $juices[FOO] juice.";
echo "\n";
echo "He drank some ${juices['FOO']} juice.";
echo "\n";
echo "He drank some {$juices['FOO']} juice.";
```

Impossible detect `${` and `}` for first example. Maybe we can add options `syntax`:
1. syntax: simple, curly: false
2. syntax: simple, curly: true
3. syntax: complex

**Comment by ichiriac** [comment]
:+1: I'll fix it soon

**Comment by evilebottnawi** [comment]
Looks due this problem we break code:
Input:
```php
$var = "This is my array value: $anArray[key]";
$var = "This is my array value: {$anArray[key]}";
```

Output:
```php
$var = "This is my array value: $anArray[key]";
$var = "This is my array value: $anArray[key]";
```

Second expression output (with `{` and `}` no):
```shell
PHP Warning:  Use of undefined constant key - assumed 'key'
```

**Comment by evilebottnawi** [comment]
I look on https://github.com/nikic/PHP-Parser/issues/500, they don't have information about `{` and `}`. After investigate and testing difference examples of code i find what we should introduce `EncapsedItem` node and have `curly` property for this. It is allow to avoid adding `curly` to `variable/*lookup/call` nodes and save ast clear.
