### ISSUE TITLE
allow trailing comma for grouped namespaces

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#177]
Input:
```php
use Foo\Bar\{
    Foo,
    Bar,
    Baz,
};
```

from CHANGELOG:

> impl #83 : Adding full support for PHP 7.2

PHP link http://php.net/manual/en/migration72.new-features.php#migration72.new-features.trailing-comma-in-grouped-namespaces

**Comment by ichiriac** [comment]
should be fixed, I'll fix few more bugs before releasing

**Comment by ichiriac** [comment]
released under 3.0.0-prerelease.3
