### ISSUE TITLE
strange with parens and unary

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#181]
Input:
```php
$a = (-100);
$a = -(100);
```
First is `number` with `-`, second is `unary` operation.

How this do `babylon` https://astexplorer.net/#/gist/09d3bbd44f6274b78370283e4b780e68/c641a63b7a2a9ed776568165db4d2af13341738e

**Comment by ichiriac** [comment]
:+1: I'll upgrade it

**Comment by evilebottnawi** [comment]
Looks we fix it and released :+1: So we can close issue.
