### ISSUE TITLE
[bug] difference ast for staticlookup and parens

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#186]
```php
echo Foo::$bar['baz'];
echo (Foo::$bar)['baz'];
```

Ast for first line should be same as for second.

**Comment by ichiriac** [comment]
related to #182 - the offset precedence is not handled

**Comment by ichiriac** [comment]
This bug was fixed :

![image](https://user-images.githubusercontent.com/173203/50773040-f0bc3400-128f-11e9-8cef-f1fb9e270a85.png)
