### ISSUE TITLE
[discussion] new arguments vs anonymous class arguments

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#187]
Input:
```php
$a = new Foo($arg, $arg, $arg);
```

In this case `new` node contains `argument` property with arguments and it is looks good.

But:
```php
new class ($arg, 'string', 2100, $var ? true : false, $other_arg, function () { return 1; }) extends SomeClass implements SomeInterface {
    public function log($msg)
    {
        echo $msg;
    }
};
```

In this case `new` node contains `arguments` too. I think when we use `anonymous class`, `arguments` property with arguments should belong to `class` node.

They followed by `class` keyword, but maybe i am wrong.

**Comment by ichiriac** [comment]
Not sure it would be consistent into the class node definition. The new instantiate a class structure, the class keyword defines a class structure. Arguments at the class initialisation (and passed to the constructor) are only used on instanciation actions, by using the new keyword, so they are attached on it. Here we mix both concepts, but the responsibilities are the same, the new instantiate (with specified parameters) and class defines. 

IMO it seems ok, it follows the SRP principle.

**Comment by evilebottnawi** [comment]
You are right
