### ISSUE TITLE
release 0.1.0

### ISSUE THREAD

**Issue by ichiriac** [glayzzle/php-parser#19]
Entire rewrite of the lexer. 

Some benchmark results `npm run bench`  :

```
--- parsing files - actual lexer version :
Tokens extracted      : 1375000
Tokens by sec (x1000) : 2077.6
Total duration        : 661.8 ms
Memory                :  160 kb

--- parsing files - jison lexer version :
Tokens extracted      : 1373000
Tokens by sec (x1000) : 251.8
Total duration        : 5452.2 ms
Memory                :  223 kb

--- parsing files - plain PHP version :
Tokens extracted      : 1375000
Tokens by sec (x1000) : 1838.1
Total duration        : 748.1 ms
Memory                :  256 kb

--- results Actual vs Jison :
Is 724% more rapid
Use 28% less memory

--- results Actual vs PHP :
Is 13% more rapid
Use 38% less memory

--- results Jison vs PHP :
Is 629% more slower
Use 13% less memory
```

Looking for help in order tests / increase code coverage (@nevadascout ?)

Pending fixme/todo :
- [x]  passing all php7 syntax updates
- [x]  cover over 80% of code (and 90% of lexer)
- [x]  bad column implementation
- [x]  handle columns and lines revert

**Comment by nevadascout** [comment]
If I get some time this weekend I'll look at writing some tests for this!

**Comment by ichiriac** [comment]
Notice that I've cleaned the AST structure to avoid null statements : https://github.com/glayzzle/php-parser/commit/1a7aabccf371019a76495c94b646560e3f3be6ec

It may not break your code, but that changes a bit the structure of AST

**Comment by ichiriac** [comment]
The 'USE' ast is now on a single level : https://github.com/glayzzle/php-parser/commit/ed12cdcdaa78c3198dab90b77ede9a5ed7ddf031 

It may break your parser, in principle the final release MUST not have plain nested arrays.

The rules are the following :

* each node must be an array (no nulls or other type of vars)
* the first offset of any node contains its type (so plain nested arrays are not allowed)

A bad AST sample :
```js
['program', [
  null, // <- not an array
  [  
    ['use' .... // <-- not a node type
    ['use' ....
  ]
]]
```

**Comment by ichiriac** [comment]
Previous benchmark was made with php 5.6 from windows, and a simple token codebase. 

With php 7.0.1 and the column implementation results are low (and the token tests are more complex) :

```
--- parsing files - actual lexer version :
Tokens extracted      : 2283000
Tokens by sec (x1000) : 757.2
Total duration        : 3015.1 ms
Memory                :  185 kb

--- parsing files - jison lexer version :
Tokens extracted      : 2290000
Tokens by sec (x1000) : 73.4
Total duration        : 31202.9 ms
Memory                :  231 kb

--- parsing files - plain PHP version :
Tokens extracted      : 2268000
Tokens by sec (x1000) : 1690.5
Total duration        : 1341.6 ms
Memory                :  0 kb

--- results Actual vs Jison :
Is 935% more rapid
Use 20% less memory

--- results Actual vs PHP :
Is 125% more slower
Use 100% more memory

--- results Jison vs PHP :
Is 2226% more slower
Use 100% more memory
```

And here exact same benchmark with php 5.6.8 : 

```
--- array vs object for storing AST :
Array Write 1.7 ms
Object Write 1.7 ms
Array Memory 90.560546875 kb
Object Memory 90.343359375 kb
Array Read 0.3 ms
Object Read 2.5 ms

--- parsing files - actual lexer version :
Tokens extracted      : 2283000
Tokens by sec (x1000) : 817.5
Total duration        : 2792.5 ms
Memory                :  183 kb

--- parsing files - jison lexer version :
Tokens extracted      : 2290000
Tokens by sec (x1000) : 66.1
Total duration        : 34631.3 ms
Memory                :  230 kb

--- parsing files - plain PHP version :
Tokens extracted      : 2282000
Tokens by sec (x1000) : 522.4
Total duration        : 4368 ms
Memory                :  512 kb

--- results Actual vs Jison :
Is 1140% more rapid
Use 20% less memory

--- results Actual vs PHP :
Is 56% more rapid
Use 64% less memory

--- results Jison vs PHP :
Is 693% more slower
Use 55% less memory
```

> Note that actual benchs are not really accurate being run from windows, but anyway, the PHP 7 parser is 3 times more rapid than PHP 5.6, and this parser is about 2 times more slow than PHP 7. Did not take in account disk I/O, these numbers are only relevant with millions of tokens and with slow disk I/O the gap should not be so huge.

NB : There is room for some optimisations
