### ISSUE TITLE
[bug] impossible detect `var` and invalid `visibility: 'public'` in property

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#190]
```php
class Foo
{
    var $var0;
    public $var1;
}
```

Can't detect `var`, also `$var0` has `visibility: 'public'`, it is truth, but it is not good for `parse`. PHP-Parser use other node type for this https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/PrettyPrinter/Standard.php#L682, but for me it is unnecessary, if we set `visibility: null` it is allow detect what we should use `var`.

**Comment by ichiriac** [comment]
be aware that : when using `var` the `visibility` property is null, and when the visibility descriptor is missing the `visibility` property is an empty string.

```php
<?php
class foo {
  static $foo; // visibility is empty
  var $bar; // visibility is null
}
```
