### ISSUE TITLE
[feature] add rawValue property for nowdoc/heredoc

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#191]
```php
<<<'EOF'
EOF;

<<<'EOF'

EOF;
```

`value` is empty for both nodes, in theory we can get newline from `raw`, but `raw` contains many unnecessary characters (`label`, `quotes`, `<<<`), maybe we can add `rawValue` property which contains only raw value:
- `` for first.
- `\n` for second.

**Comment by evilebottnawi** [comment]
Also i find bug, look on `raw` property - first node contains raw value for first and second node

**Comment by ichiriac** [comment]
here still a little bug on the raw value :

![image](https://user-images.githubusercontent.com/173203/48840769-e9000900-ed8f-11e8-90e0-4078514a8e34.png)

**Comment by ichiriac** [comment]
@evilebottnawi can we close this issue ? I see a merged PR
