### ISSUE TITLE
[bug] no leading comments in offset of `propertylookup`

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#193]
Input:
```php
<?php 

$a = $var
    // Comment
    ->each() ;
```

`each` doesn't have `leadingComments`. Example from babylon https://astexplorer.net/#/gist/10e1259460e97f43e102343e9f86ff0f/e06c03bd57464f336a3ea68530eeeff01bfef30b

**Comment by ichiriac** [comment]
it's fixed, but not sure how to reproduce this case : https://github.com/glayzzle/php-parser/blob/master/src/parser/variable.js#L58 - if you find a way to cover this path, it may contain the bug also
