### ISSUE TITLE
[feature] Convert silent mode to a property

### ISSUE THREAD

**Issue by ichiriac** [glayzzle/php-parser#195]
Same idea as `parenthesizedExpression`, use a new property that replace the `silent` node with a `silent` property (true/undefined) in order to reprensent the `@` symbol.

Related issues : #177 and #170

**Comment by evilebottnawi** [comment]
I think it is invalid because https://github.com/php/php-src/blob/php-7.4.0beta4/Zend/zend_language_parser.y#L986, i.e. `silent` node contains expression, it is invalid to convert this to property
