### ISSUE TITLE
Get position from var name

### ISSUE THREAD

**Issue by marcobraghim** [glayzzle/php-parser#197]
Is there some way to get position by var name?

(Sorry to create it here, but I really don't know where would be the right place for it...)

**Comment by ichiriac** [comment]
Hi @marcobraghim,

It's the right place here. 

- First take a look at the object structure of a code here : https://glayzzle.com/
- You can also read the AST specification from here : https://glayzzle.com/php-parser/

Depending on what you try to achieve, scan recursively the AST, find nodes with kind == "variable", and next extract their name property and the location property, you should find what you need.

Provide a gist or a code sample if you need more help.

**Comment by marcobraghim** [comment]
Thanks for your answer. So I was in the right path =)
Here is the code I wrote to get a list of similar 'kind' elements:

_Ps.: Cursor is because I'm writing a Brackets plugin with it so this recursive function (method) will run only for code above the mouse cursor position._

```javascript
findBlocks = function(objs, kind) {
    var $this = this
    var result = []
    // var scopeBlocks = "namespace|class|if|else|elseif|try|catch|finally|method|function|for|foreach|"

    if (undefined === kind) {
      kind = 'assign'
    }

    if (typeof objs === 'object') {
      for (var i in objs) {
        var item = objs[i]

        if (null === item) {
          continue
        } else if (item.hasOwnProperty('loc')) {

          // Already below the current line?
          if (item.loc.start.line > $this.cursor.line) {
            break

          }
        }

        // Get arguments
        if (item.hasOwnProperty('arguments')) {
          for (var a in item.arguments) {
            if (item.arguments[a].kind === 'parameter') {
              result.push(item.arguments[a])
            }
          }
        }

        if (item.hasOwnProperty('kind') && kind.indexOf(item.kind) !== -1) {
          result.push(item)
        } else {
          result = result.concat($this.findBlocks(item, kind))
        }
      }
    }
    return result
  }
```
