### ISSUE TITLE
[bug] comment location overlaps with node location for `static` node

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#199]
Input:
```
// Comment
static
    // Comment
    $a // Comment
    // Comment
    =
    // Comment
    2021;
```

**Comment by ichiriac** [comment]
Not sure that's a bug, here the AST output :
![image](https://user-images.githubusercontent.com/173203/47264919-ee173180-d51f-11e8-900a-97f661cf43d0.png)

The comment includes the last "\n" char, so it ends at the 18th offset position. The static node starts at the 18th offset, in principle it's not an overlap.

Or do you mean it overlaps with inner comments ?

**Comment by ichiriac** [comment]
@evilebottnawi ping ?

**Comment by evilebottnawi** [comment]
@ichiriac I think problem on our side, don't have time on this issue right now and it is not high priority issue, i will investigate in near future and close issue if problem on our side and send a PR with fix if problem here

**Comment by evilebottnawi** [comment]
Fixed after implement new ast for `static`
