### ISSUE TITLE
[feature] impossible detect `namespace` keyword

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#200]
Input:
```php
$obj = new namespace\Another;
```

In name we have only `Another`.

**Comment by ichiriac** [comment]
The namespace part is a keyword and not really a namespace name part. Take a look at the 4th example on this page : http://php.net/manual/en/language.namespaces.nsconstants.php

```php
<?php
$obj = new namespace\Another;
// is not resolved exactly as the same as
$obj = new Another;
// but in 99% of cases it's strictly the same, the first version is just disabling the fallback on resolution engine 
```

Take a look at the resolution property, it's based on http://php.net/manual/en/language.namespaces.rules.php

The first is RN :
![image](https://user-images.githubusercontent.com/173203/47264998-68948100-d521-11e8-8231-bf5fa912c4bc.png)


The second UQN : 
![image](https://user-images.githubusercontent.com/173203/47264990-4d297600-d521-11e8-9c88-4fb064eb5957.png)
