### ISSUE TITLE
`resolvePrecedence` break location for `bin` nodes

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#230]
Input:
```php
$var1 + $var2 + $var3;
```

Any ideas how we can fix it? I try but it looks very difficult :confused: 
/cc @ichiriac

**Comment by ichiriac** [comment]
not sure but the resolve precedence is only supposed to move nodes, not their location, so the only introduced problem could be to rename some property, like `what` that could become something else and used here : https://github.com/glayzzle/php-parser/blob/master/src/ast.js#L204

I need to look more in details, but in principle should not break any node location, just their orders

**Comment by ichiriac** [comment]
Hi @evilebottnawi, I've checked and everything seems correct, I don't see any bug

**Comment by ichiriac** [comment]
Ok, got it, the problem is not on vars location, but on bin nodes

**Comment by ichiriac** [comment]
it's resolved, now offsets are correctly updated - it's fixed also on retif, cast and assign

**Comment by ichiriac** [comment]
released in `3.0.0-prerelease.8`
