### ISSUE TITLE
[bug] call should be in ExpressionStatement

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#239]
Input:
```php
call();
```

Now we don't have `ExpressionStatement`.

**Comment by evilebottnawi** [comment]
Same problem for:
```php
Foo::$var;
```

**Comment by ichiriac** [comment]
We introduced the `ExpressionStatement` as a fallback statement here : 
https://github.com/glayzzle/php-parser/blob/master/src/parser/statement.js#L378

... But it concerns every expression related statement that `expectEndOfStatement`, so it was missed :
- https://github.com/glayzzle/php-parser/blob/master/src/parser/statement.js#L364
- ... and almost every expression that expects an `expectEndOfStatement`

I'll fix this case, but we need to cover every kind of expression that uses `expectEndOfStatement`. The `return`, `break` ... and other types of statements are already including `;` so no need to decorate them

**Comment by ichiriac** [comment]
It's fixed, with this bugfix you can safely say ExpressionStatement => consume(expression) + ';'
