### ISSUE TITLE
Wrong value when using octal notation, hexadecimal notation and unicode codepoint escaped characters in string

### ISSUE THREAD

**Issue by ganlvtech** [glayzzle/php-parser#245]
http://php.net/manual/en/language.types.string.php#language.types.string.syntax.double

Test script:

```php
<?php
echo "\n"; // linefeed (LF or 0x0A (10) in ASCII)
echo "\r"; // carriage return (CR or 0x0D (13) in ASCII)
echo "\t"; // horizontal tab (HT or 0x09 (9) in ASCII)
echo "\v"; // vertical tab (VT or 0x0B (11) in ASCII) (since PHP 5.2.5)
echo "\e"; // escape (ESC or 0x1B (27) in ASCII) (since PHP 5.4.4)
echo "\f"; // form feed (FF or 0x0C (12) in ASCII) (since PHP 5.2.5)
echo "\\"; // backslash
echo "\$"; // dollar sign
echo "\""; // double-quote
echo "\141"; // octal notation
echo "\x61"; // hexadecimal notation
echo "\u{0061}"; // Unicode codepoint, which will be output to the string as that codepoint's UTF-8 representation (added in PHP 7.0.0)
```

Normal escape chars `\n\r\t\v\e\f\\\$\"` got expected results.

But octal notation `"\141"`, hexadecimal notation `"\x61"` and unicode codepoint `"\u{0061}"` are not parsed properly. The `raw` is OK, but `value` are not `a`s.

Tested on commit https://github.com/glayzzle/php-parser/blob/64cd69d4cb2bb1bb2348239f2868c95a84a331f8/src/lexer/strings.js#L85-L126

May be related with https://github.com/glayzzle/php-parser/issues/130 https://github.com/glayzzle/php-parser/issues/116

**Comment by ganlvtech** [comment]
https://github.com/nikic/PHP-Parser/blob/90ee36a7fcef4f27446148b67cd2a45abe783170/lib/PhpParser/ParserAbstract.php#L753

**Comment by evilebottnawi** [comment]
@ganlvtech thanks for issue, can you send a PR?
