### ISSUE TITLE
Compatibility with browserify

### ISSUE THREAD

**Issue by chris-l** [glayzzle/php-parser#25]
Hey! I just created a [demo](https://chris-l.github.io/php-unparser/) for php-unparser (that of course uses php-parser), inspired by the [demo of escodegen](https://estools.github.io/escodegen/demo/index.html).

I decided to do it by wrapping both php-parser and php-unparser using browserify, but browserify wasn't able to do it!

The reason was that both of them were doing `require` with `fs.readdirSync`, and it seems browserify don't like that. So I changed php-unparser to have the requires directly added (I'm using a makefile to automate that) and then browserify was able to wrap it.

In the case of php-parser, I replaced the blocks of `readdirSync` with something like this:
```
[
    require('./lexer/comments.js')(api, tokens),
    require('./lexer/initial.js')(api, tokens),
    require('./lexer/numbers.js')(api, tokens),
    require('./lexer/property.js')(api, tokens),
    require('./lexer/scripting.js')(api, tokens),
    require('./lexer/strings.js')(api, tokens),
    require('./lexer/tokens.js')(api, tokens),
    require('./lexer/utils.js')(api, tokens)
].forEach(function (ext) {
    for(var k in ext) {
      api[k] = ext[k];
    }
});
```
With that change I was able to browserify php-parser.

I think it would be nice if php-parser was able to be directly browserified. But of course, is your project and you can decide not to do it.

Also, I'm not saying you should do it like that. Perhaps you would prefer to do it some other way or automatically add the requires, or maybe you do know how to make browserify to process the files even with `readdirSync` - I wasn't able to do it.

**Comment by ichiriac** [comment]
It's fine, I was planning to do so (later) for being browser compliant, and I knew the fs statements will be a problem.

As I run it sometimes from windows, I would prefer a grunt or gulp way instead of makefile, in order to keep a nodejs/npm toolkit.

If you have time, you could make a pull request for changes, no need for a dynamic way to lookup js files, your method is just fine.

By the way, you could use https://github.com/mafintosh/browserify-fs if one day you must browserify fs calls (but in this project it's not necessary, I've used FS just because I was lazy)

**Comment by chris-l** [comment]
Ok, I  just did it #26

**Comment by ichiriac** [comment]
:+1:  thanks for your contribution, I think before closing this ticket I will :

- [ ]  Install a build system with grunt
- [ ] Release a minified version
- [ ] Release as a bower library
- [ ] Make a demo page with tokens and AST like yours (I like the idea)

BTW, it will also handle comments (next push) and it will be helpful for rebuilding the PHP code

**Comment by chris-l** [comment]
Oh, have you seen the demo page of esprima? http://esprima.org/demo/parse.html
I think their concept really fits a parser

**Comment by chris-l** [comment]
Yes, comments will be interesting to add!
