### ISSUE TITLE
Leading comments are treated as trailing comments to the previous function body

### ISSUE THREAD

**Issue by aameen951** [glayzzle/php-parser#250]
Hello,

I'm trying to parse the following file:
```
<?php
/** function 1 summary
 * @param Type $var Description
 **/
function FunctionName1(Type $var = null)
{
}

/** function 2 summary
 * @param Type $var Description
 **/
function FunctionName2(Type $var = null)
{
}
```

The output of the library is as follows:
```
...
{
  "kind": "function",
  "leadingComments": [{"kind": "commentblock","value": "/** function 1 summary\r\n * @param Type $var Description\r\n **/"}],
  "name": {
    "kind": "identifier",
    "name": "FunctionName1"
  },
  ...
  "body": {
    "kind": "block",
    "children": [],
    "trailingComments": [{"kind": "commentblock","value": "/** function 2 summary\r\n * @param Type $var Description\r\n **/"}]
  }
}
...
```
The problem is that the documentation of the FunctionName2 is treated as a trailing comment on the body of FunctionName1 instead of a leading comment on FunctionName2.

**Comment by ichiriac** [comment]
That comes from the parser, the way it was implemented. In some cases the documentation block may be attached as `trailingComments`, only if no other tag comes after, on the same level ...

Here another bug, on the same idea - `// bar` is attached to `foo` as a `trailingComments`

```
foo();
// bar
bar();
```

I'll try another approach - the first implementation was way too simplistic :smile:

**Comment by aameen951** [comment]
@ichiriac Thank you!

I'll find a way to tell npm to install php-parser with this fix or I might just wait until prerelease.9

**Comment by ichiriac** [comment]
I hope to release it this month but meanwhile use the commit id it will be safer as the current version may be introduce breaking changes

**Comment by danilopolani** [comment]
@ichiriac Any update on this? You can reproduce the bug as well with this: https://astexplorer.net/#/gist/d493a13a7b2ed670ccab73f6aea0c872/latest

**Comment by ichiriac** [comment]
@danilopolani, it's normal, actually not yet released - will be done this week-end
