### ISSUE TITLE
better ast for expression for lookup node

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#254]
Ref: https://github.com/glayzzle/php-parser/commit/0452f0cf8ff148ea4e63c12717944406fa6582f3

Input:
```php
class Foo {
    public $quantity = 10;

    public $foo = 12;
}

$obj = new Foo();

const quantity = 'foo';

echo $obj->{quantity};
```

I think we need implement new node ast instead using `literal`, because it is not literal (also literal should contain `raw`, but here we don't need `raw` value), i think better name for this `PropertyLookupExpression`, what do you think? I can made PR.

**Comment by ichiriac** [comment]
related to #251 

Now it's fixed : `$var = $bar->${$property};`

```js
Program {
  kind: 'program',
  children:
   [ ExpressionStatement {
       kind: 'expressionstatement',
       expression:
        Assign {
          kind: 'assign',
          operator: '=',
          left: Variable { kind: 'variable', name: 'var', curly: false },
          right:
           PropertyLookup {
             kind: 'propertylookup',
             what: Variable { kind: 'variable', name: 'bar', curly: false },
             offset:
              Variable {
                kind: 'variable',
                name:
                 Variable { kind: 'variable', name: 'property', curly: false },
                curly: true } } } } ],
```

> Implementation is explained here : https://github.com/glayzzle/php-parser/issues/251#issuecomment-464443836
