### ISSUE TITLE
[documentation] dead link in README.md

### ISSUE THREAD

**Issue by khalyomede** [glayzzle/php-parser#265]
**Explaination**
In the documentation, the link [https://github.com/glayzzle/php-parser/blob/master/docs/parser.md](https://github.com/glayzzle/php-parser/blob/master/docs/parser.md) is dead.

**Reproduce the issue**
Click on **Documentation > Parser API** link to reproduce the issue.

**Expected result**
To be redirected to some page.

<hr />

Awesome lib by the way :)

**Comment by ichiriac** [comment]
Thanks @khalyomede,

The documentation was moved some time ago, links are now fixed. If you want to play around, start with the sandbox, and then when you implement it use the nodes API reference.

BR,
Ioan
