### ISSUE TITLE
Implement a Noop node

### ISSUE THREAD

**Issue by ichiriac** [glayzzle/php-parser#272]
In order to avoid Null values, or to keep track on empty statements for example.

Related for example to https://github.com/glayzzle/php-parser/pull/267

**Comment by evilebottnawi** [comment]
:+1: Good idea

**Comment by ichiriac** [comment]
related to #174

**Comment by ichiriac** [comment]
related to #135

**Comment by ichiriac** [comment]
It's done, but should now be introduced in various cases :

In principle on every property that is an arrayof elements, with the possibility to have an empty set :

```
<?php function foo() { /* 1 */ } ?>
<?php class foo { /* 1 */ } ?>
<?php namespace foo { /* 1 */ } ?>
<?php /* 1 */ ?>
```
