### ISSUE TITLE
Incorrect parsing of backslash-prefixed use declarations

### ISSUE THREAD

**Issue by Loilo** [glayzzle/php-parser#291]
This came up over at [prettier/php-plugin#1029](https://github.com/prettier/plugin-php/issues/1029).

The following code throws a syntax error where it shouldn't:

```php
<?php

use \A, \B, \C;
```

This seems to be due to the parser not accepting leading backslashes in untyped use declarations of use groups. However, due to the nature of the parser implementation, it does not show before the third use item (`use \A, \B;` works fine).

I've fixed this locally and will attach a PR shortly.

**Comment by ichiriac** [comment]
Hi @Loilo, many thanks for your PR - I will release it soon

**Comment by Loilo** [comment]
MY pleasure. 🙂
