### ISSUE TITLE
Case which is not consistent with Zend PHP parser

### ISSUE THREAD

**Issue by eou** [glayzzle/php-parser#348]
```php
f(&$a = 1);
```
It should throw a parse error:
```
Parse error: syntax error, unexpected '&'
```

**Comment by ichiriac** [comment]
Hi @eou 

In php 7 - some by reference usage becomes deprecated - Some examples :

```
php -r "[&\$a] = [1];"
PHP Fatal error:  [] and list() assignments cannot be by reference in Command line code on line 1

php -r "&\$a = \$foo;"
PHP Parse error:  syntax error, unexpected '&', expecting end of file in Command line code on line 1

php -r "\$a = &time();"
PHP Notice:  Only variables should be assigned by reference in Command line code on line 1

php -r "\$a = &new Date();"
PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in Command line code on line 1

php -r "print(&\$a);"
PHP Parse error:  syntax error, unexpected '&' in Command line code on line 1

php -r "print(\$a = &\$b);"
=> PASS

php -r "\$a = &\$b;"
=> PASS
```

**Comment by evilebottnawi** [comment]
@ichiriac i think we should parser them, because we are parser :smile:

**Comment by ichiriac** [comment]
Hi @evilebottnawi, I will only handle parse errors, others are handled at runtime, ou building time, they no more a part of the parser. But if you still need to retrieve these informations you can pass the flag `suppressErrors: true`, the parser will ignore the token and continue to parse the rest of the file.

**Comment by evilebottnawi** [comment]
I mea we should handle all cases except syntax error, for example:
``
php -r "[&\$a] = [1];"
PHP Fatal error:  [] and list() assignments cannot be by reference in Command line code on line 1
```

```
php -r "\$a = &time();"
PHP Notice:  Only variables should be assigned by reference in Command line code on line 1
```

should be parsed

**Comment by ichiriac** [comment]
:+1:  of course, I'll handle and raise only parse errors
