### ISSUE TITLE
revert byRef node

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#359]
https://github.com/glayzzle/php-parser/commit/fbfd46f7401c468ef38eac9e50b5ac8ed35cde9c

Why 

https://github.com/glayzzle/php-parser/commit/fbfd46f7401c468ef38eac9e50b5ac8ed35cde9c#commitcomment-34836285?

**Comment by ichiriac** [comment]
duplicate / lets continue on #205 - it's the same thread
