### ISSUE TITLE
implement `heredoc` node instead using `encapsed`

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#368]
Yes, `heredoc` and `encapsed` are similar, but will be great have other node for this.

Anyway i want to hear other opinions

**Comment by ichiriac** [comment]
Hi @evilebottnawi,

Not sure to understand, can you provide an example of an encapsed that should be an `heredoc` or else ?

**Comment by evilebottnawi** [comment]
@ichiriac https://github.com/glayzzle/php-parser/issues/371#issuecomment-525535487, we just need new `heredoc` node here instead using `encapsed` node for `heredoc` syntax

**Comment by czosel** [comment]
Seems like this has been implemented in the `prettier` branch, which has been merged.
