### ISSUE TITLE
dirty ast

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#370]
Input:
```php
test;
```

Output `identifier` with `classreference` name, it is invalid, in our code base `classreference` === `name` from php, so it should be only `classreference` node

**Comment by ichiriac** [comment]
Here the error :
https://github.com/glayzzle/php-parser/blob/master/src/parser/variable.js#L60

Should `return = name`  instead of `result = result("identifier", name);`

 @evilebottnawi, if you have some time to check it and do a PR

**Comment by ichiriac** [comment]
it's fixed, waiting to be released, please check the commit, i've introduced the nullkeyword node (was missing)
