### ISSUE TITLE
nowdoc have unnecessary property `quote`

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#371]
The `nowdoc` syntax should be always use `'` quotes, so this property is unnecessary.

**Comment by ichiriac** [comment]
Nowdoc node is used with heredoc, and heredoc can use `"` or without any quote - https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc - the solution could be to create a new node `heredoc` with a quote property (as a boolean).

**Comment by evilebottnawi** [comment]
Right now we have `nowdoc` ast node where we have `quote` property, but we don't need this property because `nowdow` **always** require single quotes `'`

**Comment by evilebottnawi** [comment]
Fixed in `prettier` branch and will be merged in future (i hope)
