### ISSUE TITLE
Refactor php flags to a version string

### ISSUE THREAD

**Issue by ichiriac** [glayzzle/php-parser#386]
Instead using `php73`, use just a `version` property :

```
const ast = parser.parseCode(`
<?php$var = 1; ?>
`, { 
    parser: {
      debug: true,
      php73: true
    },
    ast: {
      withPositions: true,
      withSource: true
    }
  }
);
```

Becomes :

```
const ast = parser.parseCode(`
<?php$var = 1; ?>
`, { 
    parser: {
      debug: true,
      version: '7.3'
    },
    ast: {
      withPositions: true,
      withSource: true
    }
  }
);
```

The version is converted to a number `7.3` => `703` (major * 100 + minor)

/cc @evilebottnawi  It will be easier to check compatibilities without handling many tags

**Comment by ichiriac** [comment]
related to #387 - bad design to handle the version flag (defaults etc)

**Comment by ichiriac** [comment]
should also handle multiple versions `['5.0', '7.0']` (related to #401)

**Comment by evilebottnawi** [comment]
Good idea, i will look on this in near future
