### ISSUE TITLE
can't parse

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#401]
Input:
```
$var = &new Foo();
```

Maybe it is already parsable, but default mode is php7, we should try to parse in php7 when try to parse in php5 by default if not specified other

**Comment by ichiriac** [comment]
I would prefer to avoid unwanted behaviors. Lets keep defaults, and introduce a missing `php5` flag with `false` by default :

And in order to parse, the `&` will be allowed on `new` only on `php5` mode instead the `!php7` mode

```js
const ast = parser.parseEval(`
$var = &new Foo();
`, { 
    parser: {
      debug: true,
      php5: true,
      php7: true
    },
    ast: {
      withPositions: true,
      withSource: true
    }
  }
);
```

**Comment by ichiriac** [comment]
Hi @evilebottnawi, sorry but this can't be fixed as it's compliant to php deprecation, you can have php7 and php5 mixed codes into the same repositiory (or same file) ...

Here the code line to remove : https://github.com/glayzzle/php-parser/blob/fdd8c152449c054537d1e37cc87149fad9397fd3/src/parser/expr.js#L519

If you want to introduce a patch you can still run php-parser with to following option :

```
const parser = phpParser.declare({
  parser: {
  /**
   * Reads assignment
   * @param {*} left
   */
  read_assignref: function(result, left) {
    this.next();
   const right = this.token === this.tok.T_NEW ? this.read_new_expr() : this.read_variable(false, false);
    return result("assignref", left, right);
  }
  }
})
```
