### ISSUE TITLE
release first stable 3.0

### ISSUE THREAD

**Issue by ichiriac** [glayzzle/php-parser#465]
Hi @evilebottnawi, @czosel,

I would like to release this week the first stable, with full support up to PHP 7.4. After this release we can still continue publishing bugfixes and new features, but no more breaking changes on this milestone. 

Could you please take a look at the backlog and identify missing features with breaking changes to integrate on this version, or create issues if they does not exists.

Here for example the kind of breaking change before releasing : [Refactor php flags to a version string](https://github.com/glayzzle/php-parser/issues/386)

Depends on complexity and priority, but maybesome feature may be moved on v4 later release.

**Comment by czosel** [comment]
Hi @ichiriac 

Sounds great! Refactoring the version flags into a version string seems like a good idea. I went through the backlog and found some issues that might still make sense for 3.0:

https://github.com/glayzzle/php-parser/issues/62 (most important i guess)
https://github.com/glayzzle/php-parser/issues/362
https://github.com/glayzzle/php-parser/issues/135
https://github.com/glayzzle/php-parser/issues/272 (not sure if we'd consider this to be breaking?)

**Comment by ichiriac** [comment]
#62 : not a lot of work to be done, just a check on bodies, already refactored some important parts
#362: easy to do, I'm on it
#135: not easy but very important, and related on #272
#272 : could be breaking as they are introduced in new nodes, example : `<?php /** foo **/ ?>` will be a noop with the comment attached to it

[Script tags & AST Structure / Introducing Breaking Changes](https://github.com/glayzzle/php-parser/issues/170) - I think we can put on version 4 - not ready and may require some work

--- 

I've created a milestone for this release : https://github.com/glayzzle/php-parser/milestone/10 - if needed, you can still change the milestone of an issue

**Comment by ichiriac** [comment]
Hi  @evilebottnawi, @czosel,

The first 3.0 stable version is ready to be released, you can try on master, it fixes the following :
https://github.com/glayzzle/php-parser/milestone/10?closed=1

Unless you find something blocking, I'll release it tonight under 3.0.1 - if needed I will release bugfixes more frequently after

**Comment by czosel** [comment]
Hi @ichiriac 

Awesome that we're approaching this milestone! :tada: 
I just tried the new "noop" nodes - and it'll need some work over at prettier (see https://github.com/prettier/plugin-php/pull/1303). It might make sense to wait a little longer with the release until we have confirmed this works as expected?

**Comment by ichiriac** [comment]
ok, lets wait until next week, no need to hurry, I'll wait your go

**Comment by ichiriac** [comment]
@czosel any news ? Ithink I will take some time this week-end to prepare the release

**Comment by czosel** [comment]
Hi @ichiriac, unfortunately I'm a bit short on time again and https://github.com/prettier/plugin-php/pull/1303 is still not finished. I'll try to take a look on the weekend!

**Comment by czosel** [comment]
@ichiriac tests are passing over at https://github.com/prettier/plugin-php/pull/1303 :tada:

**Comment by ichiriac** [comment]
great, I'll release today, and then I'll release bugfixes once a week if needed
