### ISSUE TITLE
Flexible nowdoc contains extra linebreak

### ISSUE THREAD

**Issue by czosel** [glayzzle/php-parser#468]
"Classic" nowdoc nodes contain no trailing linebreak in `value`, while flexible ones do.

```php
echo <<<'EOD'
Example of string
spanning multiple lines
using heredoc syntax.
EOD;
```

```
        Nowdoc {
          "kind": "nowdoc",
          "label": "EOD",
          "raw": "<<<'EOD'
Example of string
spanning multiple lines
using heredoc syntax.
EOD",
          "value": "Example of string
spanning multiple lines
using heredoc syntax.",
        },
```

Input:
```php
echo <<<'EOD'
  Example of string
  spanning multiple lines
  using heredoc syntax.
  EOD;

```

```
        Nowdoc {
          "kind": "nowdoc",
          "label": "EOD",
          "raw": "<<<'EOD'
  Example of string
  spanning multiple lines
  using heredoc syntax.
  EOD",
          "value": "Example of string
spanning multiple lines
using heredoc syntax.
",
        },
```

**Comment by ichiriac** [comment]
Hi @czosel,

The `value` property is in principle the computed value, as in PHP there is no trailing space even with this syntax at the evaluation time it's good for me.

Here you're just missing the `indent` property meaning that the node used whitespace indentation over the `value`, or if you don't need the rewrite the nowdoc syntax, you can just use the `raw` property.

**Comment by ichiriac** [comment]
Hi @czosel, I've read again with more attention your issue, you are right, my previous answer still can be implemented also, bug you're right, it's a bug
