### ISSUE TITLE
Nodes positions in the AST

### ISSUE THREAD

**Issue by fredericlb** [glayzzle/php-parser#5]
Hi,

I was wondering if an option could be added to the library API that would add positional metadata concerning each node in the AST.

ie : 

```
phpParser.evalCode(..., {locations: true})
// -> would return an AST with a location member for each node such as : 
// {start: {row: 3, col: 5}, end: {row: 3, col: 11}}
```

I have looked at the existing code and while these locations are saved by the lexer, they are not kept by the parser. Do you think it would be difficult to add this behaviour to the library ? The only way I've found to add this information is to change every functions in the parser directory in order to append locations to the returned lists, but it would be quite difficult to do.

**Comment by ichiriac** [comment]
Hi Frederic,

It makes sense, you could also add an offset position for start & end. Your request may not be hard to implement, I suggest to make a decorator function and to replace the returned lists with it.

An example :

```js
// into src/parser.js 
  createNode: function(name) {
    var startAt = null;
    if (this.options.locations === true) { 
      startAt  = {
         line: this.lexer...,
         ...
      };
    }
    return function() {
      var result =  Array.prototype.slice.call(arguments);
      result.unshift(name);
      if (this.options.locations === true) {
         result = { 
           node: result, 
           start: startAt,
           end: {
             line: this.lexer...,
             ...
           }
        };
      }
      return result;
    }.bind(this);
  }
```

And the usage will be :

```js
// into array.js for example

read_array: function(vars) {
      var expect = null;
      var items = [];
      var result = this.createNode('array');
      
      if (this.expect([tokens.T_ARRAY, '[']).token == tokens.T_ARRAY) {
        this.next().expect('(');
        expect = ')';
      } else {
        expect = ']';
      }
      if (this.next().token != expect) {
        while(this.token != EOF) {
          items.push(this.read_array_pair_list());
          if (this.token == ',') {
            this.next();
            if (this.token === expect) {
              break;
            }
          } else break;
        }
      }
      this.expect(expect).next();
      return result(items);
    },
```

If you have some time to kill, you are wellcome to make a pull request

**Comment by gliwka** [comment]
Hi @ichiriac,

I've seen that this feature has already been implemented in some parts, although the location is still missing around most AST nodes.

Are you still working on this feature? If not, would you accept a contribution? Just want to make sure, that there's no duplicate effort spent on the same issue.

Best wishes,
Matthias

**Comment by ichiriac** [comment]
Hi Matthias,

For now I don't have time to spend on the project so your help would be **highly** appreciated and any contribution is of course. The master is up to date and there is no local pending commits. 

It would be also great while you implement nodes positions to cover them with tests : https://github.com/glayzzle/php-parser/tree/master/test/functional - I plan to improve the tests coverage.

I've seen your project, that's a great idea :+1:, and it could be used in grunt or an ide like atom.

Best Regards,
Ioan
