### ISSUE TITLE
expression as generator key

### ISSUE THREAD

**Issue by czosel** [glayzzle/php-parser#532]
Input:
```
<?php

function foo() {
  $test = 123;
  yield "bar {$test}" => 123;
}
```

Output:
```
Parse Error : syntax error, unexpected '"', expecting ';' on line 5
```

I didn't test it with just the parser yet; the original bug report is https://github.com/prettier/plugin-php/issues/1390.

**Comment by ichiriac** [comment]
Hi @czosel, the problem is fixed, I'll release this soon

**Comment by czosel** [comment]
Awesome, thank you! :tada:
