### ISSUE TITLE
"Invalid body indentation level" error when using flexible nowdoc and variable interpolation

### ISSUE THREAD

**Issue by loilo** [glayzzle/php-parser#560]
The following PHP code fails to be parsed by `parseCode()` with an "Invalid body indentation level" error:

```php
<?php

$x = <<<'NOWDOC'
    ...
    NOWDOC;

$y = "_$z";
```

<details>
<summary>Detailed error stack</summary>

```
SyntaxError: Invalid body indentation level (expecting an indentation at least 4) on line 7
    at parser.raiseError (node_modules/php-parser/src/parser.js:330:17)
    at parser.check_heredoc_indentation_level (node_modules/php-parser/src/parser/scalar.js:136:14)
    at parser.remove_heredoc_leading_whitespace_chars (node_modules/php-parser/src/parser/scalar.js:63:10)
    at parser.read_encapsed_string_item (node_modules/php-parser/src/parser/scalar.js:343:18)
    at parser.read_encapsed_string (node_modules/php-parser/src/parser/scalar.js:445:23)
    at parser.read_scalar (node_modules/php-parser/src/parser/scalar.js:271:23)
    at parser.read_expr_item (node_modules/php-parser/src/parser/expr.js:489:19)
    at parser.read_expr (node_modules/php-parser/src/parser/expr.js:18:19)
    at parser.read_expr_item (node_modules/php-parser/src/parser/expr.js:419:46)
    at parser.read_expr (node_modules/php-parser/src/parser/expr.js:18:19) {
  lineNumber: 7,
  fileName: 'eval',
  columnNumber: 7
}
```

</details>

The interesting thing here is the combination: the error appears when *all* of the following conditions are met:

- `$x` is assigned with a **Nowdoc** block (not Heredoc).
- That Nowdoc block is a **flexible** Nowdoc, i.e. the closing marker must be indented.
- The string assigned to `$y` **needs** to have an **interpolated variable** (`$z` in the example).
- The string assigned to `$y` **needs** to have a **character before the interpolation**. I picked the underscore in this example, but basically any character will suffice.

  Notable **exceptions that will not trigger the error** are the following:
  - Spaces
    ```php
    $y = " $z";
    ```
  - Newlines
    ```php
    $y = "\n$z";
    ```
  - a single Backspace (as it escapes the interpolation)
    ```php
    $y = "\$z";
    ```
  - an opening brace as part of an interpolation-enclosing pair:
    ```php
    $y = "{$z}";
    ```

It appears to me that the flexible Nowdoc is not properly "closed" by the parser and it tries to apply Nowdoc rules to the next string as well: If 4 spaces are added to the start of the string like this:

```php
$y = "    _$z";
```

...the parser will accept that.

**Comment by hackel** [comment]
Another test case that is triggering this error:
```
SyntaxError: Invalid body indentation level (expecting an indentation at least 16) on line 266
[error]   264 |             $mpdf->WriteHTML($stylesheet, HTMLParserMode::HEADER_CSS);
[error]   265 |             $mpdf->WriteHTML($htmlContent, HTMLParserMode::HTML_BODY);
[error] > 266 |             $mpdf->Output($tempPath = public_path("/exports/delivery-orders/{$book->hash}.pdf"));
[error]       |                                                                            ^
```
The quoted snippet is preceded proceeded immediately by an indented NOWDOC:
```php
            $mpdf->SetHTMLFooter(<<<'HTML'
                <div class="footer">
                    Some boring static HTML
                </div>
                HTML);
```
