### ISSUE TITLE
Issue with comment

### ISSUE THREAD

**Issue by bsauveton** [glayzzle/php-parser#6]
Great job with this module, It's almost perfect but the parseCode method is skipping the comment.
We would like to use the parser to decompose and rewrite our php class (in order to enrich them), but, it's actually impossible to rewrite without the comments (for obvious reason).
Is it possible to add this feature to your module?
Regards.

**Comment by bsauveton** [comment]
ps : i have try to put this.lexer.all_tokens = true; but an error is triggered.

**Comment by ichiriac** [comment]
The lexer.all_tokens is used to filter (or not) extra tokens that are not handled by the ast grammar builder :

```js
lexer.lex = function() {
  var token = lex.call(this);
  if (!this.all_tokens) {
    while(
      token === T_WHITESPACE      // ignore white space
      || token === T_COMMENT      // ignore single lines comments
      || token === T_DOC_COMMENT  // ignore doc comments
      || (
        !this.mode_eval // ignore open/close tags
        && (
          token === T_OPEN_TAG
        )
      )
    ) {
      token = lex.call(this);
    }
    if (!this.mode_eval && token == T_OPEN_TAG_WITH_ECHO) {
      // open tag with echo statement
      return T_ECHO; 
    }
  }
  return token;
};
```

As you can see it filters any `T_WHITESPACE`, `T_COMMENT`, `T_DOC_COMMENT` tokens.

When parsing and building an AST tree it avoids to handle these tokens and are ignored from the grammar point of view (that's why you get a parse error when you enable it)

I'm agree with you, php if not strongly typed, so without `T_DOC_COMMENT` statements attached to functions, classes, etc ... you loose some usefull informations.

The short answer to your request is : yes it can be done. I've started to specify this function here : https://github.com/glayzzle/php-parser/wiki/annotations and you are welcome to make proposals.

**Comment by bsauveton** [comment]
Thanks for your answer, so as i see in your specification, regular comments won't be parsed ?

**Comment by ichiriac** [comment]
Give me please an example of a regular comment that you'd like to be parsed.

IMO the AST should only contain information about the program flow, simple comments that are used by the reader to better understand what the code does is not useful into the AST. 

Do you have counter examples, or use cases ?

**Comment by bsauveton** [comment]
To be clear, we don't want to just analyse the code, we want to take any custom php class, even one already modified by the user, parse it, add some "stuff" in it and then recreate the php file. In that case, we cannot erase the comments.
Regards.

**Comment by ichiriac** [comment]
Oh ok, I better understand your needs (did not read all your first comment). It's nearly impossible to do what you're expecting.

The AST is structured, the code also, but comments can break the code logic. For example :

```php
<?php 
$a = /* some comment */ true;
// AST WITHOUT COMMENT SHOULD BE
['program', [
  ['set', ['var', 'a'], ['const', true]]
]]
// BUT WHERE TO PUT THE COMMENT NODE ?
['program', [
  ['comment', 'some comment'],
  ['set', ['var', 'a'], ['const', true]]
]]
// THE RESULTING OUTPUT AFTER REBUILD COULD BE :
/* some comment */
$a = true;
```

Also you will need to keep spacing formattings (? or you can reformat automatically), the AST is only related to tokens, so you will have a node for that also, and it's the same problem as the comments.

IMO I think that the AST is not meant to store this kind of extra informations, but as you mention, that could be helpfull for manipulating the code.

Also texts nodes are no more keeped ordered, with the ast you will have a list of methods, constants, properties, so you would not be able to rebuild this kind of structure :

```php
<?php
class foo {
  public $bar;
  // a comment here ... but attached where ?
  const BAZ = '123';
  protected $foobar = false;
  function __construct() {
  }
  private $bam;
  public function getBam() {
    return $this->bam;
  }
}
```

At the rebuild step, you will have all properties together, methods together, constants together. As you see you should (?) consider to attach in this case the comment to const, and here it would be a comment property but not a node.

Could you tell me the stuff you want to add into the code, I maybe can help you, in private by mail to `i dot chiriac at yahoo dot com` if you don't want to tell it publicly.

Anyway, thanks for the issue, I've planned a long time ago to parse comments :)

**Comment by rasmusbe** [comment]
Hi,

I am also interested in getting the comments, and I looked at how the `token_get_all` function in php does it, and I think we should do something similar.

This code:
```php
<?php
$tokens = token_get_all( "<?php
class foo {
  public \$bar;
  // a comment here ... but attached where ?
  const BAZ = '123';
  protected \$foobar = false;
  function __construct() {
  }
  private \$bam;
  public function getBam() {
    return \$this->bam;
  }
}" );

foreach ( $tokens as $token ) {
	if ( is_array( $token ) ) {
		printf(
			'Line %d: %s (%s)',
			$token[2],
			token_name($token[0]),
			htmlspecialchars($token[1])
		);
		echo PHP_EOL;
	}
}
```

gives me this:
```
Line 1: T_OPEN_TAG (<?php
)
Line 2: T_CLASS (class)
Line 2: T_WHITESPACE ( )
Line 2: T_STRING (foo)
Line 2: T_WHITESPACE ( )
Line 2: T_WHITESPACE (
  )
Line 3: T_PUBLIC (public)
Line 3: T_WHITESPACE ( )
Line 3: T_VARIABLE ($bar)
Line 3: T_WHITESPACE (
  )
Line 4: T_COMMENT (// a comment here ... but attached where ?
)
Line 5: T_WHITESPACE (  )
Line 5: T_CONST (const)
Line 5: T_WHITESPACE ( )
Line 5: T_STRING (BAZ)
Line 5: T_WHITESPACE ( )
Line 5: T_WHITESPACE ( )
Line 5: T_CONSTANT_ENCAPSED_STRING ('123')
Line 5: T_WHITESPACE (
  )
Line 6: T_PROTECTED (protected)
Line 6: T_WHITESPACE ( )
Line 6: T_VARIABLE ($foobar)
Line 6: T_WHITESPACE ( )
Line 6: T_WHITESPACE ( )
Line 6: T_STRING (false)
Line 6: T_WHITESPACE (
  )
Line 7: T_FUNCTION (function)
Line 7: T_WHITESPACE ( )
Line 7: T_STRING (__construct)
Line 7: T_WHITESPACE ( )
Line 7: T_WHITESPACE (
  )
Line 8: T_WHITESPACE (
  )
Line 9: T_PRIVATE (private)
Line 9: T_WHITESPACE ( )
Line 9: T_VARIABLE ($bam)
Line 9: T_WHITESPACE (
  )
Line 10: T_PUBLIC (public)
Line 10: T_WHITESPACE ( )
Line 10: T_FUNCTION (function)
Line 10: T_WHITESPACE ( )
Line 10: T_STRING (getBam)
Line 10: T_WHITESPACE ( )
Line 10: T_WHITESPACE (
    )
Line 11: T_RETURN (return)
Line 11: T_WHITESPACE ( )
Line 11: T_VARIABLE ($this)
Line 11: T_OBJECT_OPERATOR (->)
Line 11: T_STRING (bam)
Line 11: T_WHITESPACE (
  )
Line 12: T_WHITESPACE (
)
```

**Comment by ichiriac** [comment]
Hi,

You can already do the same thing as PHP, and get the same result by doing this :

```js
var engine = require('php-parser');
var EOF = engine.lexer.EOF;
engine.lexer.mode_eval = false;
engine.lexer.all_tokens = true;
engine.lexer.setInput(["<?php",
"class foo {",
"  public $bar;",
"  // a comment here ... but attached where ?",
"  const BAZ = '123';",
"  protected \$foobar = false;",
"  function __construct() {",
"  }",
"  private \$bam;",
"  public function getBam() {",
"    return \$this->bam;",
"  }",
"}"].join("\n"));
var token = engine.lexer.lex() || EOF;
var names = engine.tokens.values;
while(token != EOF) {
  console.log(entry, engine.lexer.yylineno, ':', names[token], '(', engine.lexer.yytext, ')');
  token = engine.lexer.lex() || EOF;
}
```

The hard part in this issue is not to retrieve comments from the lexer, they are already retrieved, but to build an AST structure with them, mainly because the AST must be structured, and the comments have no insertion rule and could break the code logic.

I thinks the only way to implement this, is to parse and attach comments node only before functions, classes, traits, interfaces, and properties members. All other comments will be ignored, and each of this AST node will have an offset for the comment structure.

**Comment by ichiriac** [comment]
Hi, I've found a clean solution here : https://github.com/glayzzle/php-parser/wiki/Annotations#ast-structure

This concerns only doc blocks `/**...*/`. I plan to do the following :

* doc blocks will be retrieved and stored in a buffer, and ignored from AST
* when a node uses the positions helper, the docblock will be parsed and injected as a decorator (same as the positions)

To test this algorithm in the next release I will attach doc nodes without parsing them, just sending their plain text into the `offset1`.

**Comment by ichiriac** [comment]
first light implementation, only extract documents blocks when needed : https://github.com/glayzzle/php-parser/commit/54a4521df433c3c6ce9eb284f526df502c21a5cc

**Comment by ichiriac** [comment]
I'm closing this issue because comments are now implemented. The parsing of annotations are made in another project with a more high level of abstraction : https://github.com/glayzzle/php-reflection/blob/master/src/comment/parser.js
