### ISSUE TITLE
New release to NPM

### ISSUE THREAD

**Issue by nevadascout** [glayzzle/php-parser#7]
I'd love to use the new node locations feature, but to do that I'd have to manually copy the source and reference it in my project.

Is it possible to have a new version with the latest changes released onto NPM?

Thanks!

**Comment by rom1504** [comment]
Before it gets released, you could use npm git dependencies (put "glayzzle/php-parser" instead of the version number)

**Comment by nevadascout** [comment]
@rom1504 Thanks for the tip!

**Comment by ichiriac** [comment]
thanks @rom1504
