### ISSUE TITLE
Online Demo Error

### ISSUE THREAD

**Issue by cseufert** [glayzzle/php-parser#72]
When loading https://glayzzle.com/php-parser/ in Chrome 58.0.3029.110 (64-bit)

I get this error in the console, and the parser does not seem to work:
```
(index):155 Uncaught ReferenceError: JSONEditor is not defined
    at (index):155
(anonymous)	@	(index):155
```

**Comment by ichiriac** [comment]
Hi @cseufert,

Thanks for the report, the rawgit CDN I used was broken, I replaced it with cloudflare so it should be way more stable ^^
