### ISSUE TITLE
Code style: Use prettier

### ISSUE THREAD

**Issue by Selion05** [glayzzle/php-parser#723]
I'm working on  php8 attributes right now and the es-lint rules annoy me quite a bit. 

e.g. I always use single quotes and let prettier decide what to use automatically. Here it just tells me the error without fixing it.

Maybe I haven't configured intellij-idea correctly - so hints on that are welcome but what do you guys think about switching to prettier? 

Also note that javascript isn't my main language so I might have overlooked something!

**Comment by czosel** [comment]
We are using prettier already! We're using the default configuration, which means double quotes instead of single quotes. ESlint just makes sure that the prettier formatting is respected. Could it be that your IDE is using a custom configuration for prettier?

**Comment by Selion05** [comment]
:facepalm: my bad. I didn't find a prettier config file so I didn't activate it.
