### ISSUE TITLE
Relevant Hacker News Thread

### ISSUE THREAD

**Issue by gliwka** [glayzzle/php-parser#76]
Hi @ichiriac,

there's a relevant HN thread regarding running PHP in the Browser using a babel to php transpiler:
https://news.ycombinator.com/item?id=14743724

Best,
Matthias

**Comment by gliwka** [comment]
The relevant project mentioned there is https://gitlab.com/kornelski/babel-preset-php#php7-to-es7-syntax-translator

**Comment by ichiriac** [comment]
A M A Z I N G ! 

Kudos to @pornel, I've started something similar [here](https://github.com/glayzzle/php-transpiler) but did not got time to finish it.

Congrats dude :+1:
