### ISSUE TITLE
Ternary operator is wrong

### ISSUE THREAD

**Issue by ichiriac** [glayzzle/php-parser#77]
Correct the ternary operator precedence (left).

Source code :
https://github.com/glayzzle/php-parser/blob/master/src/ast/bin.js

Check any operator from here + cover with test :
http://php.net/manual/en/language.operators.precedence.php

Related to this issue :
https://gitlab.com/kornelski/babel-preset-php/issues/3

Node shifts may also cause https://github.com/glayzzle/php-parser/issues/75 issue

**Comment by chris-l** [comment]
oh yes, I did have a situation about the ternary operator on php on a project of mine sometime ago!

I learned about that problem (and other problems) here: https://eev.ee/blog/2012/04/09/php-a-fractal-of-bad-design/
I recommend you to study that article, so you can also discover other potential issues related with php's _"unique"_ design decisions.

**Comment by ichiriac** [comment]
Hi Chris, 

Thanks for the link, sadly and I'm almost totally agree with the author. Despite I like PHP alot, so this is the kind of reason that made me start Glayzzle.

He missed one of the most important argument for me, PHP can't make survive variables between requests (and I understand why with memory leaks and no threading solution). 

Take for example a bootstrap flow : read configuration > lazy load classes > register routes and other stuf - and then start to dispatch the request. 

Doing so at each time, PHP behave more like a batch generating an HTML output instead a true web application. This situation changes with additional frameworks that make use of event oriented components http://reactphp.org/ ... so that's why I've thinked at a NodeJS transpiler.

**Comment by ichiriac** [comment]
fixed & released under 2.0.5
