### ISSUE TITLE
PHP8: static type hint

### ISSUE THREAD

**Issue by MasonD** [glayzzle/php-parser#786]
#486
Currently the parser doesn't understand that static can be used as a type hint like so: 
```php
class Foo {
    public function Bar(): static {
        return $this;
    }
}
```

**Comment by fernando-rivas-smtp** [comment]
i'm having the same problem... there is a fix or a workaround?

**Comment by alexander-akait** [comment]
We need fix problem in parser, PR welcome

**Comment by fernando-rivas-smtp** [comment]
can you give me some hint to where the problem could be? i would gladly fix it!

**Comment by fernando-rivas-smtp** [comment]
pr created: https://github.com/glayzzle/php-parser/pull/791

**Comment by genintho** [comment]
This issue was fixed, can the maintainer close it?
