### ISSUE TITLE
Function node location has incorrect end line

### ISSUE THREAD

**Issue by nevadascout** [glayzzle/php-parser#8]
The red boxes in the image below shows that the function ends on line 17, but the parser is reporting line 14 as the end.

![](http://i.imgur.com/L3vjJSs.png)

I haven't tested any other node types to see if they are affected as well

**Comment by ichiriac** [comment]
it was fixed on master

**Comment by nevadascout** [comment]
@ichiriac Confirming this is now fixed, thanks!
