### ISSUE TITLE
Null node found in short-form `if` body

### ISSUE THREAD

**Issue by motiz88** [glayzzle/php-parser#84]
In the following code (see also [AST Explorer snippet](https://astexplorer.net/#/gist/dcde248b9867b77c126e2e926dd06f43/4029a50b0d58062ef70097eb4208d89ab9680ca6)) the `if` statement's body is currently parsed as `{kind: "block", children: [null]}`.

```php
<?php if (true): ?>
<?php endif; ?>
```

I have a PR upcoming to fix and regression-test this.

**Comment by ichiriac** [comment]
Hi @motiz88, agree with you, the behaviour is a bug. Your PR is welcome :+1:

**Comment by ichiriac** [comment]
The fix is released under 2.0.7
