### ISSUE TITLE
Allow using arrays in static properties

### ISSUE THREAD

**Issue by danog** [glayzzle/php-parser#87]
Both assigning and reading a value from an array in a static property throws a `Got a MemberExpression for MemberExpression property` type error.

Example code that triggers the error:
```
<?php
class a {
    public static $a = ['a'];
    public static function test() {
        self::$a[0] = 'b';
        echo self::$a[0];
    }
}
a::test();
```

**Comment by danog** [comment]
Strange enough, using the class name instead of self works:

```
<?php
class a {
    public static $a = ['a'];
    public static function test() {
        a::$a[0] = 'b';
        echo a::$a[0];
    }
}
a::test();
```

**Comment by ichiriac** [comment]
Hi, not sure to be able to reproduce the error. 

Here your code : https://astexplorer.net/#/gist/793a9ae6d25d3ecc4b8e9349622d6848/66ad24d0112fbeef0a958579ba86a3b168855cd5

Can you send me a stack or reproduce it on astexplorer and save it as a snippet ?

**Comment by ichiriac** [comment]
Hi @danog,

I'm still not able to reproduce the error, any clues ?

**Comment by danog** [comment]
Sorry for the late response, I'm using [babel-preset-php](https://gitlab.com/kornelski/babel-preset-php.git)

**Comment by ichiriac** [comment]
Ah ok, seems that a problem directly with babel-preset-php.

I'm opening a bug report there : https://gitlab.com/kornelski/babel-preset-php/issues/13, you can continue to contribute there.

I will try to work on it this week-end.
