### ISSUE TITLE
Split multiline comments

### ISSUE THREAD

**Issue by danog** [glayzzle/php-parser#88]
php-parser does not split multiline comments.

Example code: 
```
<?php
/*
afs

fas

sfa

*/
```

Expected result: 
```
Doc {
  kind: 'doc',
  loc: 
   Location {
     source: null,
     start: Position { line: 2, column: 0, offset: 6 },
     end: Position { line: 10, column: 0, offset: 27 } },
  isDoc: false,
  lines: [ 'afs', '', '', 'fas', '', '', 'sfa' ] }
```

Actual result: 
```
Doc {
  kind: 'doc',
  loc: 
   Location {
     source: null,
     start: Position { line: 2, column: 0, offset: 6 },
     end: Position { line: 10, column: 0, offset: 27 } },
  isDoc: false,
  lines: [ 'afs\n\nfas\n\nsfa' ] }
```

**Comment by ichiriac** [comment]
It's true, the lines property may seem inconsistent. Take this [sample](https://astexplorer.net/#/gist/793a9ae6d25d3ecc4b8e9349622d6848/adee33a2a9256669d6bf5d8e6512817a45db5114) :

```php
<?php
/**
 * Line 1
 * Line 2
 * @return something
 */
function foo() {
}


/* 
 Not a doc tag
 but a multiline comment instead
*/
```

The resulting JSON is :

```js
// First block :
{
      "kind": "doc",
      "loc": {
        "source": null,
        "start": {
          "line": 2,
          "column": 0,
          "offset": 6
        },
        "end": {
          "line": 6,
          "column": 3,
          "offset": 54
        }
      },
      "isDoc": true,
      "lines": [
        "",
        "Line 1",
        "Line 2",
        "@return something",
        ""
      ]
    }

// Second block :
    {
      "kind": "doc",
      "loc": {
        "source": null,
        "start": {
          "line": 11,
          "column": 0,
          "offset": 76
        },
        "end": {
          "line": 14,
          "column": 2,
          "offset": 130
        }
      },
      "isDoc": false,
      "lines": [
        "Not a doc tag\n but a multiline comment instead"
      ]
    }
```

The main reason of this kind of differentiation is to be able to rebuild documentation tags as they were defined (used by [php-unparser](https://github.com/chris-l/php-unparser) for example), but I'm agree with you on the fact that I may not use lines in both cases, and it's really inconsistent.

I will work on this on the next release but the hard part will be that I'll break backward compatibility.

Actually if you need a consistent way to read comment lines, pass them to [doc-parser](https://github.com/glayzzle/doc-parser/) library. In principle the parsing function is compliant with all php-parser doc lines formats.

**Comment by ichiriac** [comment]
Hi @danog,

The next release will tackle this issue by providing you the raw comment contents. If you want more details on what will change take a look at https://github.com/glayzzle/php-parser/issues/126#issuecomment-370268380
