### ISSUE TITLE
Keep getting ast children as Inline

### ISSUE THREAD

**Issue by b4dnewz** [glayzzle/php-parser#89]
I'm trying for the first time this plugin that look awesome but I'm getting all the time the childrens as Inline and when I try to search for classes or else returns null.

```php
<?php 
class Test {
  function foo() {
  }
}
?>
```
```js
const contents = fs.readFileSync( './test.php' );
const ast = parser.parseCode(contents, {});
console.log('AST:', ast);
```
```bash
 kind: 'program',
  children:
   [ Inline {
       kind: 'inline',
       value: '60631121041123213101310991089711511532841011151164041321231310323213103232102117110991161051111103210211111140413212313103232323213103232125131032321310125131013106362' } 
  ],
  errors: []
```

Am I missing some option?

Many thanks in advance, awesome tool.

**Comment by b4dnewz** [comment]
I've resolved it, the trick is to use `utf8` as encoding to return a string instead of a buffer from fs.readFile function, but the documentation is tricky, [here](https://github.com/glayzzle/php-parser#api-overview) says it accepts a string buffer., it should be more precise I think.

By the way, I finally start using this great tool!

**Comment by ichiriac** [comment]
I've just saw it, confusing `String buffer` - ok, I'll add a check in order to see if you pass a buffer it will automatically be converted to a string

**Comment by b4dnewz** [comment]
@ichiriac I've forked all of the php-packages and applied some small changes and wrote a little bit of documentation, if you are interested I can make a PR for that.

I'm using php-writer, which depends on php-parser and php-unparser in a project.

**Comment by ichiriac** [comment]
yes of course, any PR is welcome
