### ISSUE TITLE
`Enum` is treated as a reserved word, even before PHP 8.1

### ISSUE THREAD

**Issue by czosel** [glayzzle/php-parser#896]
Input: `class Enum {}`
Output: syntax error, unexpected 'Enum' (T_ENUM), expecting T_STRING

The official PHP parser seems to be able to handle this example even after PHP 8.1 - if that turns out to be too difficult to fix here, maybe should consider adding the keyword only for PHP >= 8.1?

Also see https://github.com/glayzzle/php-parser/pull/895 for a failing test.

**Comment by alexander-akait** [comment]
Sounds like the same https://github.com/glayzzle/php-parser/issues/834, but for `Enum`

**Comment by czosel** [comment]
Yes, probably we should look at @ichiriac's suggestion on how to fix this: https://github.com/glayzzle/php-parser/issues/834#issuecomment-1038368182

**Comment by czosel** [comment]
Fixed in `3.1.0-beta.6` :tada:

**Comment by czosel** [comment]
Fixed in `v3.1.0-beta.9` :tada:

**Comment by jaulz** [comment]
@czosel thanks a lot! I can confirm that it also works in real life 😉
