### ISSUE TITLE
Function node location has incorrect start colum

### ISSUE THREAD

**Issue by nevadascout** [glayzzle/php-parser#9]
In the screenshot below, the grey boxes show that the parser is reporting that the function starts at col `11` -- immediately after the `public` access modifier.

I believe it should report `4` as the start column.

![](http://i.imgur.com/L3vjJSs.png)

**Comment by ichiriac** [comment]
Hi @nevadascout,

The master is a work in progress, at the time when I've started to implement positions I had not commited all my code, and there are still bugs.

I've just commit it and made some bug fixes, it should now work better.

Take a look at this file : https://github.com/glayzzle/php-parser/blob/master/test/position.js and tell me if you find others issues.

Actually you can find locations over functions, traits, classes, interfaces, properties, methods. It's still missing a lot of nodes, the work is in progress and I've not tested yet everything.

Also be aware that i've changed the location of visibility flags over methods and properties : 
https://github.com/glayzzle/php-parser/commit/824aff359cbac7c0c781e09805e222324d2dd21f

**Comment by nevadascout** [comment]
Thanks for the quick reply + many changes!

I'm fully aware that the entire parser is a work in progress - I just wanted to make sure you were aware of this bug :)

If I find any more issues I'll let you know.
