### ISSUE TITLE
[Question] Is there a feature to parse phpdoc?

### ISSUE THREAD

**Issue by yaegassy** [glayzzle/php-parser#944]
Is there a parser for `phpdoc`? Or does `php-parser` itself have that feature? I am looking for the purpose of parsing php-parser's `leadingComments`.

**Comment by czosel** [comment]
Hi @yaegassy, I assume you're looking for a parser that is written in JavaScript, and not https://github.com/phpstan/phpdoc-parser ? I'm not aware of any project doing this.

**Comment by yaegassy** [comment]
Thanks for the reply, I am looking for a phpdoc parser written in javascript.

There was a `glayzzle/doc-parser`, but it has not been updated and is not properly available in the current php... <https://github.com/glayzzle/doc-parser>

Thanks again for the reply. 🙇
