### ISSUE TITLE
Are TS type definitions welcome as contribution

### ISSUE THREAD

**Issue by DaGhostman** [glayzzle/php-parser#96]
As the title says, I am pretty much interested in writing TypeScript definition file(s) `.d.ts`, but I am a little unsure if the correct place will be the main repository or a separate one, since if they are in the main repo that might come as an additional burden when maintaining (since they also will have to be updated accordingly)

+ as an additional side question, are there any plans for TS in general (rewriting the codebase or anything similar or you are aiming to be strictly JS)

Thanks and keep up the good work 👍

**Comment by ichiriac** [comment]
Hi @DaGhostman,

Actually I've already started a definition file here : https://github.com/glayzzle/php-parser/blob/master/index.d.ts

It works with VSCode autocompletion, but it's not commented and some functions may be missing. If you want to complete it you are welcome :)

For your second question, it could be a great idea to rewrite the library in TS as the result will be the same as JS, there is no reason to not do it, and it could provide a much greater structure. 

If you want to and you have time you can try to start a prototype, we could release it under a major release.

Thanks for your kindness :smile:

**Comment by DaGhostman** [comment]
Oh... I didn't notice the definition file in the repo (sorry 🙂 ) I will go through it and see if there can be any changes, as for the TS rewrite - I might give it a go, but can't promise anything since this is a big project and will take some time. Anyhow do you have any sort of idea when the next major will be or it is not planned for now.

**Comment by ichiriac** [comment]
I have a small bugfix pending, almost done. Currently it covers 100% of php 7.1 and some pending changes for 7.2.

If it continues like this :
- v0 was a beta based on jison parser
- v1 was full rewrite of parser
- v2 rewrite with a new ast structure

So I'll keep increasing v2 until I make breaking changes on the API.

So the next major release is not planned, I may either be a breaking change but still on current structure, or introducing a new technology with a major rewrite like passing it on typescript.

Actually I would like to focus on fully covering latest syntax releases of PHP7, try to improve speed, and decrease source size if possible.

I have no time to spend on the project this year, but I should be free and have more time in few month, so next year I would like to work and finish some satellite projects around php-parser and maybe release a functional version of the glayzzle projet :crossed_fingers:

**Comment by ichiriac** [comment]
Hi @DaGhostman, it's an old issue/conversation, I'll close it in order to decrease the issues counter,

**Comment by DaGhostman** [comment]
Sorry for the delay and lack of participation, I was (and unfortunately still am) too occupied with work and can't find any spare time to look into ... well anything. I will try to contribute in some way as soon as I get some spare time on my hands.

Sorry for the downer :disappointed:

**Comment by ichiriac** [comment]
no worries, it's just for fun, come when you can
