### ISSUE TITLE
using kind:inline is adding <?php at the end 

### ISSUE THREAD

**Issue by hrachbkweb** [glayzzle/php-parser#99]
Thanks for library ).
Here is my issue
`  {
      "kind": "program",
      "children": [
        {
          "kind": "inline",
          "value": " $builder->add('task')\n    ;"
        }
      ],
      "errors": []  
    }`
 this suppose to output ` $builder
        ->add('task');` 
 instead this is the output ` $builder
        ->add('task') ;<?php ;`

Any idea ?

**Comment by ichiriac** [comment]
Hi,

This library does not output PHP code, you are maybe using a library like this one : 
https://github.com/chris-l/php-unparser ?

**Comment by ichiriac** [comment]
Hi @hrachbkweb,

I don't grasp the issue with `php-parser`, I'll close the issue but fell free to come back and comment if it's still a problem for you, and I'll re-open it then.

BR,
Ioan
